# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy to Firebase"
  lane :deploy do
    begin
      firebase_app_distribution(
        groups: "tester",
        release_notes: "Bug fixed and improvements.",
        apk_path: "app/build/outputs/apk/release/app-release.apk",
        app: ENV['FIREBASE_APP_ID'],
        firebase_cli_path: "/usr/local/bin/firebase",
        firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      )
    end
  end
end
