name: Mikro POS build and run test
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: build and run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Clean Build
        run: ./gradlew clean
      - name: Build apk Debug
        run: ./gradlew assembleDebug
      - name: Run Test
        run: ./gradlew test